#!/bin/bash

TAG=${1:-latest}
REGISTRY="images.pkgrepo.bcbssc.com/web3270"

docker images --format "{{.Repository}}" | grep '^bridge_server-' | while read -r img
do
    echo "Tagging: $img:$TAG"

    docker tag "$img:latest" \
        "$REGISTRY/$img:$TAG"

    docker push \
        "$REGISTRY/$img:$TAG"
done
docker images | grep "$TAG"
