#!/bin/sh
# WebTerm/3270 Bridge — port configuration
# Called automatically by start.sh on first run, or directly to reconfigure.

echo ""
echo "WebTerm/3270 Bridge — Setup"
echo "==========================="
echo ""

# Read existing value with grep — never source .env (avoids executing arbitrary lines)
CURRENT_PORT=8081
if [ -f .env ]; then
  STORED=$(grep '^BRIDGE_HOST_PORT=' .env 2>/dev/null | cut -d= -f2 | tr -d '[:space:]')
  [ -n "$STORED" ] && CURRENT_PORT="$STORED"
  echo "Existing configuration found — press Enter to keep current values."
  echo ""
fi

printf "Bridge UI port (what you type in the browser) [%s]: " "$CURRENT_PORT"
read -r INPUT_PORT
BRIDGE_HOST_PORT="${INPUT_PORT:-$CURRENT_PORT}"

# Validate: must be a number in range
case "$BRIDGE_HOST_PORT" in
  ''|*[!0-9]*) echo "Invalid — using $CURRENT_PORT."; BRIDGE_HOST_PORT=$CURRENT_PORT ;;
esac
if [ "$BRIDGE_HOST_PORT" -lt 1 ] || [ "$BRIDGE_HOST_PORT" -gt 65535 ] 2>/dev/null; then
  echo "Port out of range — using $CURRENT_PORT."; BRIDGE_HOST_PORT=$CURRENT_PORT
fi

cat > .env << EOF
# WebTerm/3270 Bridge — local configuration
# Generated by setup.sh — edit manually or re-run './start.sh --setup' to reconfigure.
# This file is gitignored and never committed.

BRIDGE_HOST_PORT=${BRIDGE_HOST_PORT}
EOF

echo ""
echo "Saved. Bridge UI → http://localhost:${BRIDGE_HOST_PORT}"
echo ""
