#!/bin/sh
# WebTerm/3270 Bridge — port configuration
# Called automatically by start.sh on first run, or directly to reconfigure.

echo ""
echo "WebTerm/3270 Bridge — Setup"
echo "==========================="
echo ""
printf "Bridge UI port (what you type in the browser) [8081]: "
read -r INPUT_PORT
BRIDGE_HOST_PORT="${INPUT_PORT:-8081}"

# Validate: must be a number in range
case "$BRIDGE_HOST_PORT" in
  ''|*[!0-9]*) echo "Invalid — using 8081."; BRIDGE_HOST_PORT=8081 ;;
esac
if [ "$BRIDGE_HOST_PORT" -lt 1 ] || [ "$BRIDGE_HOST_PORT" -gt 65535 ] 2>/dev/null; then
  echo "Port out of range — using 8081."; BRIDGE_HOST_PORT=8081
fi

cat > .env << EOF
# WebTerm/3270 Bridge — local configuration
# Generated by setup.sh — edit manually or re-run './start.sh --setup' to reconfigure.
# This file is gitignored and never committed.

BRIDGE_HOST_PORT=${BRIDGE_HOST_PORT}
EOF

echo ""
echo "Saved. Bridge UI → http://localhost:${BRIDGE_HOST_PORT}"
echo ""
